spring:
  application:
    name: book-service

server:
  port: 9091

datasource:
  url: jdbc:h2:mem:bookdb
  driverClassName: org.h2.Driver
  username: sa
  password:

jpa:
  database-platform: org.hibernate.dialect.H2Dialect

h2:
  console:
    enabled: true